
name: Node.js CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --save-dev cross-env    
    - run: npm install
    - run: npm run bootstrap
    - run: npm run link
    - run: npm run build
    - run: npx lerna run release
    - name: Read package version
      uses: gagle/package-version@v1.0.0    
    - run: tar -cjvf ncform-${{ steps.package-version.outputs.version }}.tar.gz --exclude ./node_modules --exclude ./test --exclude ./mock  -C packages/ncform .  
    - run: tar -cjvf ncform-common-${{ steps.package-version.outputs.version }}.tar.gz --exclude ./node_modules --exclude ./test --exclude ./mock  -C packages/ncform-common .  
    - run: tar -cjvf ncform-theme-elementui-${{ steps.package-version.outputs.version }}.tar.gz --exclude ./node_modules --exclude ./test --exclude ./mock  -C packages/ncform-theme-elementui .  
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.package-version.outputs.version }}
        artifacts: "ncform-*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
